### ISSUE TITLE
Simplify the tests to isolate the source of slowness

### ISSUE THREAD

**Issue by anescobar1991** [mattblang/jest-image-comparison-perf-repro#1]
Would you accept a PR to remove puppeteer and the navigating to a browser bit and to instead compare against static images in the file system?

That way we can isolate even more where the problem may be and remove unnecessary steps to reproduce.

**Comment by theblang** [comment]
Absolutely! I was actually working on doing that at the airport a bit ago. Will push it up when I get a chance, but feel free to make any tweaks before then.
